// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountTodo() {
  return window['go']['main']['App']['CountTodo']();
}

export function CreateTodo(arg1, arg2) {
  return window['go']['main']['App']['CreateTodo'](arg1, arg2);
}

export function DelteTodo(arg1) {
  return window['go']['main']['App']['DelteTodo'](arg1);
}

export function FindAllTodo(arg1) {
  return window['go']['main']['App']['FindAllTodo'](arg1);
}

export function FindOneTodo(arg1) {
  return window['go']['main']['App']['FindOneTodo'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['main']['App']['UpdateTodo'](arg1, arg2);
}
