// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CountTodo():Promise<database.Count>;

export function CreateTodo(arg1:database.CreateInput):Promise<database.Todo>;

export function DeleteTodo(arg1:number):Promise<database.Todo>;

export function FindAllTodo(arg1:any):Promise<database.FindAllResponse>;

export function FindOneTodo(arg1:number):Promise<database.Todo>;

export function Ping():Promise<boolean>;

export function UpdateTodo(arg1:number,arg2:{[key: string]: any}):Promise<database.Todo>;
