// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CountTodo():Promise<any>;

export function CreateTodo(arg1:database.Input):Promise<any>;

export function DeleteTodo(arg1:number):Promise<any>;

export function FindAllTodo(arg1:any):Promise<Array<any>>;

export function FindOneTodo(arg1:number):Promise<any>;

export function Ping():Promise<boolean>;

export function UpdateTodo(arg1:number,arg2:database.Input):Promise<any>;
