// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountTodo():Promise<{[key: string]: number}>;

export function CreateTodo(arg1:number,arg2:{[key: string]: any}):Promise<{[key: string]: any}>;

export function DelteTodo(arg1:number):Promise<{[key: string]: any}>;

export function FindAllTodo(arg1:{[key: string]: any}):Promise<Array<{[key: string]: any}>>;

export function FindOneTodo(arg1:number):Promise<{[key: string]: any}>;

export function Ping():Promise<boolean>;

export function UpdateTodo(arg1:number,arg2:{[key: string]: any}):Promise<{[key: string]: any}>;
